### ISSUE TITLE
Plugin Settings question

### ISSUE THREAD

**Issue by fmika** [pr49sc/apex-plugin-datetimepicker#1]
For Timepicker I can see only Format time and Default time parameters. The other two - Step time and
Round time are not visible. What I am doing wrongly?
Regards,
Frantisek
![snimek obrazovky 302](https://cloud.githubusercontent.com/assets/15983291/12090873/d72c8634-b2f2-11e5-938c-84134f84d58b.png)

**Comment by pr49sc** [comment]
Hi. You found the first bug - "step time" mus be unconditional. But "Round time" is only visible, if "Default time" is null - because, if it's always 7 o'clock, the timepicker can't round the time :-)

**Comment by fmika** [comment]
Hi Steffen,
thank you for your fast reply.
Frantisek
